demo:
	python setup.py build_ext --inplace
	
	python -c "import basic;basic.print_bool(1)"
	python -c "import basic;basic.print_bool(True)"

	python -c "import basic;basic.print_integer(50)"
	python -c "import basic;basic.print_integer(50.1)"
	python -c "import basic;basic.print_integer("50.1")"
	
	python -c "import basic;basic.print_float(3.1415926535897932384626433832795)"
	python -c "import basic;basic.print_float(31415.926535897932384626433832795)"